//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTiet()
        {
            this.CongViecs = new HashSet<CongViec>();
        }
    
        public int Id { get; set; }
        public string MaSo { get; set; }
        public string Ten { get; set; }
        public int SoLuong_1_Bo { get; set; }
        public int SoLuong { get; set; }
        public string QuyCach { get; set; }
        public int SL_Phoi_1_Bo { get; set; }
        public int SL_Phoi { get; set; }
        public string QC_Phoi { get; set; }
        public string XL_Nhiet { get; set; }
        public string XL_BeMat { get; set; }
        public string GhiChu { get; set; }
        public bool PhongKT { get; set; }
        public bool DaBaoPhoi { get; set; }
        public Nullable<System.DateTime> NgayDatMua { get; set; }
        public Nullable<System.DateTime> NgayKho_HT { get; set; }
        public Nullable<System.DateTime> NgayXCK_HT { get; set; }
        public bool XCK_HT { get; set; }
        public bool PKD_Mua { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> ChiTiet_LanBaoPhoi { get; set; }
        public int ChiTiet_LenhSanXuat { get; set; }
        public Nullable<int> ChiTiet_NhanVienPKT { get; set; }
        public Nullable<int> ChiTiet_VatLieu { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<int> SlgPhoiNhap { get; set; }
        public Nullable<int> SlgPhoiXuat { get; set; }
        public Nullable<int> SlgPhoiChuaNhan { get; set; }
        public Nullable<int> SlgGiaCong { get; set; }
        public Nullable<int> SlgHoanThanh { get; set; }
        public Nullable<int> FileDinhKemCount { get; set; }
        public Nullable<int> ChiTiet_NguoiDung { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<System.DateTime> NgayYCCP { get; set; }
        public Nullable<System.DateTime> NgayDKCP { get; set; }
        public Nullable<System.DateTime> CuaPhoi { get; set; }
        public Nullable<bool> HTLR { get; set; }
        public Nullable<bool> GiaCong { get; set; }
        public Nullable<bool> DatHang { get; set; }
        public Nullable<System.DateTime> ThoiDiemCapNhatQTCN { get; set; }
        public string NguoiCapNhatQTCN { get; set; }
        public Nullable<System.DateTime> ThoiDiemLenKH { get; set; }
        public string NguoiLenKH { get; set; }
        public Nullable<bool> DaLenKeHoach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViecs { get; set; }
    }
}
