//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanXet_CanhBao
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> PhanLoai { get; set; }
        public string MaCanhBao { get; set; }
        public Nullable<int> CapDo { get; set; }
    }
}
